apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: alert-manager
  name: alert-manager-svc
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9093
    protocol: TCP
  selector:
    app: alert-manager
  type: ClusterIP